// ZissenKaihatsu/Laravel_sample_Yuma/laravel_app/resources/js/components/MyComponent.jsx
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import axios from 'axios';


export default class MyComponent extends Component {
    constructor(props) {
        super(props);
        this.state = {
            num:0,
            msg:'ok',
        };
        this.doChange = this.doChange.bind(this);
        this.doAction = this.doAction.bind(this);
    }

    doChange(event) {
        let n = event.target.value;
        this.setState((state)=>({
            num: n,
            person:null,
        }));
    }
    doAction(event) {
        this.setState((state)=>({
            msg:'wait...',
        }));
        axios.get('/hello/json/' + this.state.num)
            .then(response =>{
                let person = response.data;
                let msg = person.id + ':' + person.name
                    + ' [' + person.mail + '] ('
                    + person.age + ')';
                this.setState((state)=>({
                    person:person,
                    msg:msg
                }));
            });
    }

    render() {
        return (
            <div className="container">
                <p>{this.state.msg}</p>
                <div>
                    <input type="number" id="num"
                        onChange={this.doChange} />
                    <button onClick={this.doAction}>Click</button>
                </div>
            </div>
        );
    }
}

if (document.getElementById('mycomponent')) {
    ReactDOM.render(<MyComponent />, document.getElementById('mycomponent'));
}

// ZissenKaihatsu/Laravel_sample_Yuma/laravel_app/resources/js/components/MyComponent.vue
<template>
    <div class="container">
        <p>{{msg}}</p>
        <hr>
        <ul>
            <li v-for="(person,key) in people">
                {{person.id}}: {{person.name}} [{{person.mail}}] ({{person.age}})
            </li>
        </ul>
    </div>
</template>

<script>
import axios from 'axios';

export default {
    mounted () {
        axios.get('/hello/json')
            .then(response =>{
                this.people = response.data;
                this.msg = 'get data!';
            });
    },
    data:function(){
        return {
            msg:'wait...',
            name:'',
            people:[],
        };
    },
    methods:{
        doAction:function(){
            this.msg = 'Hello, ' + this.name + '!!';
        }
    },
}
</script>
